# Form implementation generated from reading ui file 'do_import_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Cloud_Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 490)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_import = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_import.setGeometry(QtCore.QRect(150, 350, 141, 51))
        self.pushButton_import.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(26, 95, 180);")
        self.pushButton_import.setObjectName("pushButton_import")
        self.pushButton_plaintextfile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_plaintextfile.setGeometry(QtCore.QRect(40, 290, 131, 35))
        self.pushButton_plaintextfile.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.pushButton_plaintextfile.setObjectName("pushButton_plaintextfile")
        self.lineEdit_plaintextfile = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_plaintextfile.setGeometry(QtCore.QRect(180, 290, 371, 31))
        self.lineEdit_plaintextfile.setObjectName("lineEdit_plaintextfile")
        self.comboBox_table = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_table.setGeometry(QtCore.QRect(35, 40, 511, 41))
        self.comboBox_table.setObjectName("comboBox_table")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 101, 511, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_Refresh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Refresh.setGeometry(QtCore.QRect(310, 350, 141, 51))
        self.pushButton_Refresh.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(26, 95, 180);")
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_import.setText(_translate("MainWindow", "Import"))
        self.pushButton_plaintextfile.setText(_translate("MainWindow", "CSV File"))
        self.pushButton_Refresh.setText(_translate("MainWindow", "Refresh"))
