# Form implementation generated from reading ui file 'uploadFile.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pubPathTxb = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.pubPathTxb.setGeometry(QtCore.QRect(150, 100, 411, 31))
        self.pubPathTxb.setObjectName("pubPathTxb")
        self.cipTxb = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.cipTxb.setGeometry(QtCore.QRect(150, 250, 411, 31))
        self.cipTxb.setObjectName("cipTxb")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 131, 31))
        self.label_4.setObjectName("label_4")
        self.homeBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.homeBtn.setGeometry(QtCore.QRect(10, 10, 111, 41))
        self.homeBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(26, 95, 180);")
        self.homeBtn.setObjectName("homeBtn")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 250, 131, 31))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 131, 31))
        self.label_3.setObjectName("label_3")
        self.plaTxb = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.plaTxb.setGeometry(QtCore.QRect(150, 200, 411, 31))
        self.plaTxb.setObjectName("plaTxb")
        self.getPubPath = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getPubPath.setGeometry(QtCore.QRect(560, 100, 91, 31))
        self.getPubPath.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.getPubPath.setObjectName("getPubPath")
        self.getPubBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getPubBtn.setGeometry(QtCore.QRect(70, 300, 131, 41))
        self.getPubBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"    background-color: rgb(26, 95, 180);")
        self.getPubBtn.setObjectName("getPubBtn")
        self.encryptBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.encryptBtn.setGeometry(QtCore.QRect(220, 300, 131, 41))
        self.encryptBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"    background-color: rgb(26, 95, 180);")
        self.encryptBtn.setObjectName("encryptBtn")
        self.uploadPubBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.uploadPubBtn.setGeometry(QtCore.QRect(560, 150, 91, 31))
        self.uploadPubBtn.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.uploadPubBtn.setObjectName("uploadPubBtn")
        self.uploadCipBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.uploadCipBtn.setGeometry(QtCore.QRect(560, 250, 91, 31))
        self.uploadCipBtn.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.uploadCipBtn.setObjectName("uploadCipBtn")
        self.uploadPlaintBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.uploadPlaintBtn.setGeometry(QtCore.QRect(560, 200, 91, 31))
        self.uploadPlaintBtn.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.uploadPlaintBtn.setObjectName("uploadPlaintBtn")
        self.connectBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connectBtn.setGeometry(QtCore.QRect(540, 20, 111, 41))
        self.connectBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(34, 139, 34);")
        self.connectBtn.setObjectName("connectBtn")
        self.disconnectBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.disconnectBtn.setGeometry(QtCore.QRect(520, 300, 131, 41))
        self.disconnectBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"    background-color: rgb(178, 34, 34);")
        self.disconnectBtn.setObjectName("disconnectBtn")
        self.decryptBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.decryptBtn.setGeometry(QtCore.QRect(370, 300, 131, 41))
        self.decryptBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"    background-color: rgb(26, 95, 180);")
        self.decryptBtn.setObjectName("decryptBtn")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 131, 31))
        self.label_5.setObjectName("label_5")
        self.pubFileTxb = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.pubFileTxb.setGeometry(QtCore.QRect(150, 150, 411, 31))
        self.pubFileTxb.setObjectName("pubFileTxb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Public_key path"))
        self.homeBtn.setText(_translate("MainWindow", "Home"))
        self.label_7.setText(_translate("MainWindow", "Cipher_text path"))
        self.label_3.setText(_translate("MainWindow", "Plain_text file"))
        self.getPubPath.setText(_translate("MainWindow", "Get"))
        self.getPubBtn.setText(_translate("MainWindow", "Get Public Key"))
        self.encryptBtn.setText(_translate("MainWindow", "Encypt"))
        self.uploadPubBtn.setText(_translate("MainWindow", "Upload"))
        self.uploadCipBtn.setText(_translate("MainWindow", "Select path"))
        self.uploadPlaintBtn.setText(_translate("MainWindow", "Upload"))
        self.connectBtn.setText(_translate("MainWindow", "Connect Server"))
        self.disconnectBtn.setText(_translate("MainWindow", "Disconnect"))
        self.decryptBtn.setText(_translate("MainWindow", "Decrypt"))
        self.label_5.setText(_translate("MainWindow", "Public_key file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
