# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 517)
        
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_table = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_table.setGeometry(QtCore.QRect(40, 30, 371, 41))
        self.comboBox_table.setObjectName("comboBox_table")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(45, 80, 361, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_scrollArea = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_scrollArea.setObjectName("verticalLayout_scrollArea")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_generate_keys = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_generate_keys.setGeometry(QtCore.QRect(420, 80, 141, 51))
        self.pushButton_generate_keys.setObjectName("pushButton_generate_keys")
        self.pushButton_encrypt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_encrypt.setGeometry(QtCore.QRect(420, 140, 141, 51))
        self.pushButton_encrypt.setObjectName("pushButton_encrypt")
        self.pushButton_decrypt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_decrypt.setGeometry(QtCore.QRect(420, 200, 141, 51))
        self.pushButton_decrypt.setObjectName("pushButton_decrypt")
        self.pushButton_plaintextfile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_plaintextfile.setGeometry(QtCore.QRect(40, 320, 131, 35))
        self.pushButton_plaintextfile.setObjectName("pushButton_plaintextfile")
        self.pushButton_keyfile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_keyfile.setGeometry(QtCore.QRect(40, 270, 131, 35))
        self.pushButton_keyfile.setObjectName("pushButton_keyfile")
        self.pushButton_encryptedfile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_encryptedfile.setGeometry(QtCore.QRect(40, 370, 131, 35))
        self.pushButton_encryptedfile.setObjectName("pushButton_encryptedfile")
        self.pushButton_decryptedfile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_decryptedfile.setGeometry(QtCore.QRect(40, 420, 131, 35))
        self.pushButton_decryptedfile.setObjectName("pushButton_decryptedfile")
        self.lineEdit_keyfile = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_keyfile.setGeometry(QtCore.QRect(180, 270, 381, 31))
        self.lineEdit_keyfile.setObjectName("lineEdit_keyfile")
        self.lineEdit_decryptedfile = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_decryptedfile.setGeometry(QtCore.QRect(180, 420, 381, 31))
        self.lineEdit_decryptedfile.setObjectName("lineEdit_decryptedfile")
        self.lineEdit_encryptedfile = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_encryptedfile.setGeometry(QtCore.QRect(180, 370, 381, 31))
        self.lineEdit_encryptedfile.setObjectName("lineEdit_encryptedfile")
        self.lineEdit_plaintextfile = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_plaintextfile.setGeometry(QtCore.QRect(180, 320, 381, 31))
        self.lineEdit_plaintextfile.setObjectName("lineEdit_plaintextfile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_generate_keys.setText(_translate("MainWindow", "Generate Keys"))
        self.pushButton_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.pushButton_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.pushButton_plaintextfile.setText(_translate("MainWindow", "Plaintext File"))
        self.pushButton_keyfile.setText(_translate("MainWindow", "Key File"))
        self.pushButton_encryptedfile.setText(_translate("MainWindow", "Encrypted File"))
        self.pushButton_decryptedfile.setText(_translate("MainWindow", "Decrypted File"))
