# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SignupWindow(object):
    def setupUi(self, SignupWindow):
        SignupWindow.setObjectName("SignupWindow")
        SignupWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=SignupWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_username = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(30, 50, 100, 20))
        self.label_username.setObjectName("label_username")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(150, 50, 200, 25))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(30, 100, 100, 20))
        self.label_password.setObjectName("label_password")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(150, 100, 200, 25))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_signup = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_signup.setGeometry(QtCore.QRect(150, 200, 100, 41))
        self.pushButton_signup.setStyleSheet("color: rgb(255, 255, 255);\n"
"    background-color: rgb(26, 95, 180);")
        self.pushButton_signup.setObjectName("pushButton_signup")
        self.lineEdit_password_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_password_2.setGeometry(QtCore.QRect(150, 150, 200, 25))
        self.lineEdit_password_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.label_password_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_password_2.setGeometry(QtCore.QRect(30, 150, 111, 20))
        self.label_password_2.setObjectName("label_password_2")
        SignupWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SignupWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        SignupWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SignupWindow)
        self.statusbar.setObjectName("statusbar")
        SignupWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SignupWindow)
        QtCore.QMetaObject.connectSlotsByName(SignupWindow)

    def retranslateUi(self, SignupWindow):
        _translate = QtCore.QCoreApplication.translate
        SignupWindow.setWindowTitle(_translate("SignupWindow", "Signup"))
        self.label_username.setText(_translate("SignupWindow", "Username:"))
        self.label_password.setText(_translate("SignupWindow", "Password:"))
        self.pushButton_signup.setText(_translate("SignupWindow", "Signup"))
        self.label_password_2.setText(_translate("SignupWindow", "Repeat Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignupWindow = QtWidgets.QMainWindow()
    ui = Ui_SignupWindow()
    ui.setupUi(SignupWindow)
    SignupWindow.show()
    sys.exit(app.exec())
