# Form implementation generated from reading ui file 'abac.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 401)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbUsername = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbUsername.setGeometry(QtCore.QRect(10, 10, 111, 81))
        self.lbUsername.setObjectName("lbUsername")
        self.cbResource = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbResource.setGeometry(QtCore.QRect(150, 140, 241, 41))
        self.cbResource.setObjectName("cbResource")
        self.btnOK = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(390, 140, 51, 41))
        self.btnOK.setStyleSheet("color: rgb(255, 255, 255);\n"
"    background-color: rgb(26, 95, 180);")
        self.btnOK.setObjectName("btnOK")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 110, 221, 17))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbUsername.setText(_translate("MainWindow", "Welcome "))
        self.btnOK.setText(_translate("MainWindow", "OK"))
        self.label.setText(_translate("MainWindow", "Choose your type of resources:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
