from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.homeBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.homeBtn.setGeometry(QtCore.QRect(20, 10, 111, 41))
        self.homeBtn.setObjectName("homeBtn")
        self.getPriBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getPriBtn.setGeometry(QtCore.QRect(620, 110, 131, 31))
        self.getPriBtn.setObjectName("getPriBtn")
        self.priTxb = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.priTxb.setGeometry(QtCore.QRect(140, 110, 411, 31))
        self.priTxb.setObjectName("priTxb")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 110, 131, 31))
        self.label.setObjectName("label")
        self.cipTxb = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.cipTxb.setGeometry(QtCore.QRect(140, 170, 411, 31))
        self.cipTxb.setObjectName("cipTxb")
        self.getCipBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getCipBtn.setGeometry(QtCore.QRect(620, 170, 131, 31))
        self.getCipBtn.setObjectName("getCipBtn")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 170, 131, 31))
        self.label_2.setObjectName("label_2")
        self.dataTbv = QtWidgets.QTableView(parent=self.centralwidget)
        self.dataTbv.setGeometry(QtCore.QRect(140, 290, 411, 251))
        self.dataTbv.setObjectName("dataTbv")
        self.getPubBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getPubBtn.setGeometry(QtCore.QRect(620, 60, 131, 31))
        self.getPubBtn.setObjectName("getPubBtn")
        self.pubTxb = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.pubTxb.setGeometry(QtCore.QRect(140, 60, 411, 31))
        self.pubTxb.setObjectName("pubTxb")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 131, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 230, 131, 31))
        self.label_4.setObjectName("label_4")
        self.recoverTxb = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.recoverTxb.setGeometry(QtCore.QRect(140, 230, 411, 31))
        self.recoverTxb.setObjectName("recoverTxb")
        self.selectBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.selectBtn.setGeometry(QtCore.QRect(620, 230, 131, 31))
        self.selectBtn.setObjectName("selectBtn")
        self.connectBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connectBtn.setGeometry(QtCore.QRect(640, 10, 111, 41))
        self.connectBtn.setObjectName("connectBtn")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 290, 61, 31))
        self.label_5.setObjectName("label_5")
        self.saveBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(560, 290, 111, 41))
        self.saveBtn.setObjectName("saveBtn")
        self.disconnectBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.disconnectBtn.setGeometry(QtCore.QRect(560, 340, 111, 41))
        self.disconnectBtn.setObjectName("disconnectBtn")
        
        # Thêm các trường nhập liệu cho địa chỉ IP và port
        self.ipLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ipLabel.setGeometry(QtCore.QRect(160, 10, 61, 31))
        self.ipLabel.setObjectName("ipLabel")
        self.ipInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ipInput.setGeometry(QtCore.QRect(220, 10, 141, 31))
        self.ipInput.setObjectName("ipInput")
        self.portLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.portLabel.setGeometry(QtCore.QRect(380, 10, 61, 31))
        self.portLabel.setObjectName("portLabel")
        self.portInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.portInput.setGeometry(QtCore.QRect(440, 10, 61, 31))
        self.portInput.setObjectName("portInput")
        
        self.getPubPath = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getPubPath.setGeometry(QtCore.QRect(560, 60, 51, 31))
        self.getPubPath.setObjectName("getPubPath")
        self.getPriPath = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getPriPath.setGeometry(QtCore.QRect(560, 110, 51, 31))
        self.getPriPath.setObjectName("getPriPath")
        self.getCipPath = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getCipPath.setGeometry(QtCore.QRect(560, 170, 51, 31))
        self.getCipPath.setObjectName("getCipPath")
        self.getRecPath = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getRecPath.setGeometry(QtCore.QRect(560, 230, 51, 31))
        self.getRecPath.setObjectName("getRecPath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeBtn.setText(_translate("MainWindow", "Home"))
        self.getPriBtn.setText(_translate("MainWindow", "Get Private Key"))
        self.label.setText(_translate("MainWindow", "Private_key path"))
        self.getCipBtn.setText(_translate("MainWindow", "Get Cipher Text"))
        self.label_2.setText(_translate("MainWindow", "Cipher_text path"))
        self.getPubBtn.setText(_translate("MainWindow", "Get Public Key"))
        self.label_3.setText(_translate("MainWindow", "Public_key path"))
        self.label_4.setText(_translate("MainWindow", "Recover_text path"))
        self.selectBtn.setText(_translate("MainWindow", "Select path"))
        self.connectBtn.setText(_translate("MainWindow", "Connect Server"))
        self.label_5.setText(_translate("MainWindow", "Data"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.disconnectBtn.setText(_translate("MainWindow", "Disconnect"))
        self.getPubPath.setText(_translate("MainWindow", "Get"))
        self.getPriPath.setText(_translate("MainWindow", "Get"))
        self.getCipPath.setText(_translate("MainWindow", "Get"))
        self.getRecPath.setText(_translate("MainWindow", "Get"))
        self.ipLabel.setText(_translate("MainWindow", "IP Address:"))
        self.portLabel.setText(_translate("MainWindow", "Port:"))
